name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.repository }}/react-app # 프로젝트 루트 경로로 변경

      - name: Build project
        run: npm run build
        working-directory: ${{ github.repository }}/react-app # 빌드 경로 지정

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ github.repository }}/react-app/build # 빌드 결과물 경로 지정

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: pages
        uses: actions/deploy-pages@v2
